### ISSUE TITLE
Spanish?

### ISSUE THREAD

**Issue by KatiaSishost** [Luen/quillbot-api#6]
How can i select the lang?

**Comment by Luen** [comment]
I've updated the code and added it to the NPM registry for you to use as a package: https://www.npmjs.com/package/quillbot-api

To change languages, add an options object: 
const options = {
    language: 'Spanish', // default 'English (UK)'
}
const paraphrased = await quillbot("Ahora podemos seleccionar idiomas para parafrasear.", options)
